### ISSUE TITLE
Lot of problems - Failed to upload file

### ISSUE THREAD

**Issue by UsualVII** [Hackt1vator/applera1n#21]
At first I had the problem that the library "pil" wasn't installed and nor reported in the guide, so I installed the library required with pip3 install pil, then I had the problem Permission Denied, and i've solved it, then once again "pylzss" library wasn't installed nor reported in the guide, so I installed it and solved this one too

Now another one it's here, "failed to upload file", how much errors i have to go through lol, how to solve this one?

**Comment by throwaway-acc997** [comment]
A lot of these issues you're facing are ones I'm having to deal with as an Arch user.
This really isn't a fun one for Arch users at all. I'm currently stuck on installing pylzss...

**Comment by princeofgiri** [comment]
Now I got problem like this screenshot

<img width="926" alt="Screenshot 2023-10-28 at 16 18 52" src="https://github.com/Hackt1vator/applera1n/assets/837709/fca56e46-860d-41bf-919a-040102c2b969">

**Comment by GitH1522** [comment]
> A lot of these issues you're facing are ones I'm having to deal with as an Arch user.
> This really isn't a fun one for Arch users at all. I'm currently stuck on installing pylzss...

Hi
got the same problem...
I have to download pylzss and run  : ARCHFLAGS="-arch x86_64" python3 setup.py install   (from pylzss dir)
and it works (for me)

**Comment by princeofgiri** [comment]
btw, I made PR #26
