### ISSUE TITLE
error at running applera1n.py

### ISSUE THREAD

**Issue by MageScript** [Hackt1vator/applera1n#4]
I've this error at running : python3 applera1n.py

the error message : 
_macOS 11 (1107) or later required, have instead 11 (1106) ! 
Abort trap: 6_

I've the python 3.8.9 version installed

**Comment by Hackt1vator** [comment]
You can try brew update && brew upgrade or update your python version, I tested on Python 3.10.6 and Python 3.11

**Comment by MageScript** [comment]
it's working on python 3.10.6 thank you !
